{"author":"439205512425504771","bot":true,"channel":"343299242963763200","content":"```py\nTraceback (most recent call last):\n  File \"source_file.py\", line 1, in <module>\n    taco()\nNameError: name 'taco' is not defined\n```","created":1528243061364,"id":"453709026249932801","server":"343179912196128792"}